### ISSUE TITLE
Suggestion: support sparse arrays

### ISSUE THREAD

**Issue by jaufgang** [richie5um/FlattenJS#5]
Thanks for this useful utility!
I've noticed one minor issue using it recently.  Currently, 
```
obj = {
    a: true,
    b: {
        ba: [],
        bb: [ , 1, 2, 3, 4]
    }
};
```
will flatten to 
```
// {
//     'a': true,
//     'b.bb[0]': "undefined",
//     'b.bb[1]': 1,
//     'b.bb[2]': 2,
//     'b.bb[3]': 3,
//     'b.bb[4]': 4
// }
```
because `obj.b.bb[0]` is undefined.    This is actually getting serialized as a string `"undefined"` and will stay as a string if converting back to a nested object using inflate

I think it would be an improvement to omit undefined array elements, so that that original object would flatten to 
```
// {
//     'a': true,
//     'b.bb[1]': 1,
//     'b.bb[2]': 2,
//     'b.bb[3]': 3,
//     'b.bb[4]': 4
// }
```

**Comment by jaufgang** [comment]
Actually, I haven't checked if this is a problem but it would probably be a good idea to ensure that `undefined` values for object properties are omitted as well,  or at least returned as  value `undefined` rather than the string `"undefined"`

**Comment by richie5um** [comment]
Thanks for the comment. I'm _fairly_ sure the undefined objects work fine. The case you've raised here is something I hadn't considered. I kinda like your suggestion (omit that index in the output), but also wondering if that could cause issues for some people. I'll take a look at the code and see if I can get it working.

**Comment by richie5um** [comment]
Hi,

I've taken a look and I don't see the string undefined issue you mentioned. When I run the test, it get the undefined (value?).

![image](https://user-images.githubusercontent.com/907033/110204873-4c34dd00-7e6d-11eb-823e-7f7a8ad43e09.png)

Having said that, it doesn't *exactly* recreate the original array - you end up with an undefined, rather than an 'empty' (whatever that is in javascript values).

![image](https://user-images.githubusercontent.com/907033/110204922-8e5e1e80-7e6d-11eb-87db-e80c0389c3f4.png)


I had a quick go at making the output sparse (i.e. omitting the [0] index position, but I couldn't figure out how to do that without breaking the existing logic :).

Can you double-check on your system that you really are getting a "undefined" string, as I don't see that on my environment?

**Comment by jaufgang** [comment]
Actually, on closer inspection I see that you are correct and your function  _is_ returning the value `undefined` and not a string.  I was seeing the string `"undefined"` in my code but that was actually caused by a subsequent step after calling your function.  My apologies, I should have looked at this closer before posting that.  

I still think it would be a good idea to exclude unassigned values from sparse arrays if it's possible, but for now I can just filter out undefined values. This post has some good tips for iterating over sparse arrays: https://remysharp.com/2018/06/26/an-adventure-in-sparse-arrays

Thanks for looking into this!
